In [1]:
import pandas as pd
import numpy as np
from lightgbm import LGBMClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import average_precision_score

In [2]:
df = pd.read_csv('/home/tori/behavioural-fruad-detection/data/raw/train.csv')
df2 = pd.read_csv('/home/tori/behavioural-fruad-detection/data/raw/test.csv')

df['is_test'] = 0
df2['is_test'] = 1

full = pd.concat([df, df2])
full = full.sort_values(by=["user_id", "timestamp"]).reset_index(drop=True)
full.shape

(227656, 11)

In [3]:
full['is_first_txn'] = (full['hours_since_prev_txn'] == 999).astype(int)
full['hours_since_prev_txn'] = full['hours_since_prev_txn'].replace(999, np.nan)

In [4]:
full['running_total'] = full.groupby('user_id')['amount'].cumsum()

full['past_total'] = full['running_total'] - full['amount'] 
full['past_count'] = full.groupby('user_id').cumcount()
full['past_avg_amount'] = full['past_total'] / full['past_count'] 
full['amount_ratio'] = full['amount'] / full['past_avg_amount']

filtered_user = full[full['user_id'] == 1818]
filtered_user[['amount', 'past_avg_amount', 'amount_ratio']]

full = full.drop(columns=['running_total', 'past_total', 'past_count'])

In [5]:
filtered_user[['amount', 'past_avg_amount', 'amount']]

          amount  past_avg_amount     amount
82574  17.788061              NaN  17.788061
82575  33.010191        17.788061  33.010191
82576  37.474351        25.399126  37.474351
82577  15.018893        29.424201  15.018893
82578  10.954236        25.822874  10.954236
82579   5.410091        22.849147   5.410091
82580  14.351851        19.942637  14.351851
82581  10.819577        19.143953  10.819577
82582   5.095317        18.103406   5.095317
82583  16.608058        16.658063  16.608058
82584  14.457568        16.653063  14.457568
82585  12.680154        16.453472  12.680154
82586   2.608586        16.139029   2.608586
82587  20.935129        15.098226  20.935129
82588   6.174141        15.515147   6.174141
82589   7.483825        14.892413   7.483825
82590   8.845878        14.429377   8.845878
82591  11.044716        14.100936  11.044716
82592  13.789907        13.931146  13.789907
82593  11.366749        13.923712  11.366749
82594   7.936473        13.795864   7.936473
82595  17.147700        13.516845  17.147700
82596  15.018878        13.681884  15.018878
82597  16.473972        13.740014  16.473972
82598  10.987262        13.853929  10.987262
82599  16.853545        13.739262  16.853545
82600  25.102442        13.859043  25.102442
82601   7.586703        14.275465   7.586703
82602  19.660911        14.036580  19.660911
82603   8.567789        14.230523   8.567789
82604   5.636716        14.041765   5.636716
82605   7.820848        13.770635   7.820848
82606   9.075470        13.584704   9.075470
82607  18.365481        13.448060  18.365481
82608   9.544737        13.592690   9.544737
82609  10.799825        13.477034  10.799825
82610   8.009288        13.402668   8.009288
82611  16.491943        13.256901  16.491943
82612  17.757841        13.342033  17.757841
82613  18.136065        13.455259  18.136065
82614   7.090206        13.572279   7.090206
82615  13.003477        13.414180  13.003477
82616  31.124441        13.404401  31.124441
82617  13.596652        13.816495  13.596652
82618  19.090409        13.811499  19.090409
82619  10.833020        13.928808  10.833020
82620  14.809400        13.861508  14.809400
82621   8.444852        13.881676   8.444852
82622  16.979575        13.768409  16.979575
82623   8.461123        13.833943   8.461123
82624  13.685864        13.726486  13.685864
82625  25.527127        13.725690  25.527127

In [6]:
full['country_seen_count'] = full.groupby(['user_id', 'country']).cumcount()
full['is_new_country'] = (full['country_seen_count'] == 0).astype(int)

full['merchant_seen_count'] = full.groupby(['user_id', 'merchant_category']).cumcount()
full['is_new_merchant'] = (full['merchant_seen_count'] == 0).astype(int)

In [7]:
full['is_new_country'].sum()

np.int64(22571)

In [8]:
full['is_new_merchant'].sum()

np.int64(57058)

In [9]:
filtered_user = full[full['user_id'] == 1818]
filtered_user[['country', 'is_new_country', 'merchant_category', 'is_new_merchant']]

       country  is_new_country  merchant_category  is_new_merchant
82574        4               1                 11                1
82575        4               0                 11                0
82576        4               0                  0                1
82577        4               0                 11                0
82578        4               0                 11                0
82579       12               1                  0                0
82580       12               0                  0                0
82581       12               0                 11                0
82582       12               0                 11                0
82583       12               0                 11                0
82584       12               0                  3                1
82585        8               1                 11                0
82586        8               0                 11                0
82587        8               0                 11                0
82588       12               0                 17                1
82589       12               0                 11                0
82590       12               0                 11                0
82591       22               1                 11                0
82592        6               1                  3                0
82593        6               0                 11                0
82594        6               0                 15                1
82595       29               1                  9                1
82596        1               1                 11                0
82597        1               0                 11                0
82598        1               0                 11                0
82599        1               0                 11                0
82600        1               0                 19                1
82601        1               0                 11                0
82602        1               0                 11                0
82603        1               0                 11                0
82604        1               0                 11                0
82605        9               1                 11                0
82606        9               0                 11                0
82607        9               0                 15                0
82608        9               0                 11                0
82609        9               0                 11                0
82610        9               0                 13                1
82611       10               1                 11                0
82612       10               0                  4                1
82613        0               1                  2                1
82614        0               0                 11                0
82615        0               0                 11                0
82616        0               0                 11                0
82617        0               0                 13                0
82618        0               0                 11                0
82619        0               0                 14                1
82620        0               0                  3                0
82621        0               0                 11                0
82622        0               0                 11                0
82623        0               0                 11                0
82624        0               0                 11                0
82625        0               0                  9                0

In [10]:
full = full.drop(columns=['merchant_seen_count', 'country_seen_count'])

In [11]:
full['prev_gap_1'] = full.groupby('user_id')['hours_since_prev_txn'].shift(1)
full['prev_gap_2'] = full.groupby('user_id')['hours_since_prev_txn'].shift(2)

full['avg_gap_last3'] = full[['hours_since_prev_txn', 'prev_gap_1', 'prev_gap_2']].mean(axis=1)

In [12]:
filtered_user = full[full['user_id'] == 1818]
filtered_user[['hours_since_prev_txn', 'prev_gap_1', 'prev_gap_2', 'avg_gap_last3']]

       hours_since_prev_txn  prev_gap_1  prev_gap_2  avg_gap_last3
82574                   NaN         NaN         NaN            NaN
82575               97765.0         NaN         NaN   97765.000000
82576               16471.0     97765.0         NaN   57118.000000
82577               66443.0     16471.0     97765.0   60226.333333
82578               90995.0     66443.0     16471.0   57969.666667
82579               76486.0     90995.0     66443.0   77974.666667
82580                2086.0     76486.0     90995.0   56522.333333
82581               55617.0      2086.0     76486.0   44729.666667
82582               35832.0     55617.0      2086.0   31178.333333
82583               26606.0     35832.0     55617.0   39351.666667
82584               75220.0     26606.0     35832.0   45886.000000
82585              193035.0     75220.0     26606.0   98287.000000
82586                3529.0    193035.0     75220.0   90594.666667
82587               87006.0      3529.0    193035.0   94523.333333
82588                1248.0     87006.0      3529.0   30594.333333
82589              179147.0      1248.0     87006.0   89133.666667
82590               22967.0    179147.0      1248.0   67787.333333
82591                6644.0     22967.0    179147.0   69586.000000
82592                5565.0      6644.0     22967.0   11725.333333
82593               21733.0      5565.0      6644.0   11314.000000
82594               72268.0     21733.0      5565.0   33188.666667
82595                8769.0     72268.0     21733.0   34256.666667
82596               65564.0      8769.0     72268.0   48867.000000
82597               53543.0     65564.0      8769.0   42625.333333
82598               35185.0     53543.0     65564.0   51430.666667
82599               20830.0     35185.0     53543.0   36519.333333
82600               17753.0     20830.0     35185.0   24589.333333
82601              119159.0     17753.0     20830.0   52580.666667
82602              113405.0    119159.0     17753.0   83439.000000
82603               64760.0    113405.0    119159.0   99108.000000
82604               63442.0     64760.0    113405.0   80535.666667
82605               90179.0     63442.0     64760.0   72793.666667
82606               29932.0     90179.0     63442.0   61184.333333
82607               21012.0     29932.0     90179.0   47041.000000
82608              168588.0     21012.0     29932.0   73177.333333
82609              177088.0    168588.0     21012.0  122229.333333
82610               16556.0    177088.0    168588.0  120744.000000
82611               89832.0     16556.0    177088.0   94492.000000
82612               13158.0     89832.0     16556.0   39848.666667
82613                6849.0     13158.0     89832.0   36613.000000
82614               10887.0      6849.0     13158.0   10298.000000
82615                7553.0     10887.0      6849.0    8429.666667
82616               16688.0      7553.0     10887.0   11709.333333
82617               42780.0     16688.0      7553.0   22340.333333
82618               72454.0     42780.0     16688.0   43974.000000
82619               24013.0     72454.0     42780.0   46415.666667
82620               13581.0     24013.0     72454.0   36682.666667
82621               71619.0     13581.0     24013.0   36404.333333
82622               65916.0     71619.0     13581.0   50372.000000
82623               30557.0     65916.0     71619.0   56030.666667
82624                7865.0     30557.0     65916.0   34779.333333
82625               22550.0      7865.0     30557.0   20324.000000

In [13]:
full = full.drop(columns=['prev_gap_1', 'prev_gap_2'])

In [14]:
labeled = full[full['is_test'] == 0]
unlabeled = full[full['is_test'] == 1]

In [15]:
labeled.shape
unlabeled.shape

(45531, 17)

In [16]:
full.columns

Index(['transaction_id', 'user_id', 'timestamp', 'amount', 'merchant_category',
       'country', 'device_id', 'channel', 'hours_since_prev_txn', 'label',
       'is_test', 'is_first_txn', 'past_avg_amount', 'amount_ratio',
       'is_new_country', 'is_new_merchant', 'avg_gap_last3'],
      dtype='str')

In [17]:
full = full.drop(columns=['prev_gap_2'])

KeyError: "['prev_gap_2'] not found in axis"

In [ ]:
full.columns

In [ ]:
labeled = full[full['is_test'] == 0]
unlabeled = full[full['is_test'] == 1]

In [ ]:
labeled.shape
unlabeled.shape

In [ ]:
features = ['amount', 'channel', 'hours_since_prev_txn', 'is_first_txn', 'past_avg_amount', 'amount_ratio', 'is_new_device', 'is_new_country', 'is_new_merchant', 'avg_gap_last3']
x = labeled[features]
y = labeled['label']

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42, stratify=y
)

x_train.shape
x_test.shape
y_train.mean()
y_test.mean()

In [ ]:
model = LGBMClassifier(
    random_state=42,
    verbose=-1  
)

model.fit(x_train, y_train)

y_prob = model.predict_proba(x_test)[:, 1]

In [ ]:
y_prob[:10]

In [ ]:
average_precision_score(y_test, y_prob)

In [ ]:
labeled.groupby('label')[features].mean()

In [ ]:
y_prob_train = model.predict_proba(x_train)[:, 1]
average_precision_score(y_train, y_prob_train)

In [ ]:
cutoff = labeled['amount_ratio'].quantile(0.99)
spikes = labeled[labeled['amount_ratio'] >= cutoff]
spikes['label'].mean()

In [ ]:
y_prob_train = model.predict_proba(X_train)[:, 1]
average_precision_score(y_train, y_prob_train)

In [ ]:
model2 = LGBMClassifier(
    random_state=42,
    verbose=-1,
    num_leaves=15,
    min_child_samples=200,
    learning_rate=0.05,
    n_estimators=200
)
model2.fit(X_train, y_train)
y_prob2 = model2.predict_proba(X_test)[:, 1]
average_precision_score(y_test, y_prob2)

In [ ]:
model2.feature_importances_

In [ ]:
y_prob2_train = model2.predict_proba(x_train)[:, 1]
average_precision_score(y_train, y_prob2_train)