In [1]:
import pandas as pd
import sys

print(sys.version)

3.12.15 (main, Sep 30 2026, 22:04:19) [GCC 16.2.0]

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/home/tori/behavioural-fruad-detection/data/raw/train.csv')

In [4]:
df.head()

,transaction_id,user_id,timestamp,amount,merchant_category,country,device_id,channel,hours_since_prev_txn,label
0,243747,3399,2804395,28.632151,0,11,22279,1,232259.0,0
1,88525,317,1022027,51.946133,14,14,9154,1,211366.0,0
2,214788,2095,2471000,13.033808,13,23,21154,0,33513.0,0
3,63117,2156,728428,26.546503,18,20,50757,1,4380.0,0
4,112859,4687,1304407,6.759898,2,8,12561,0,40655.0,0

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 182125 entries, 0 to 182124
Data columns (total 10 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   transaction_id        182125 non-null  int64
 1   user_id               182125 non-null  int64
 2   timestamp             182125 non-null  int64
 3   amount                182125 non-null  float64
 4   merchant_category     182125 non-null  int64
 5   country               182125 non-null  int64
 6   device_id             182125 non-null  int64
 7   channel               182125 non-null  int64
 8   hours_since_prev_txn  182125 non-null  float64
 9   label                 182125 non-null  int64
dtypes: float64(2), int64(8)
memory usage: 13.9 MB

In [6]:
df.nunique()

transaction_id          182125
user_id                   5000
timestamp               171502
amount                  182125
merchant_category           20
country                     30
device_id                 8743
channel                      2
hours_since_prev_txn     97881
label                        2
dtype: int64

In [7]:
df.groupby('user_id').size().describe()

count    5000.000000
mean       36.425000
std         5.956431
min        18.000000
25%        32.000000
50%        36.000000
75%        40.000000
max        60.000000
dtype: float64

In [8]:
df2 = pd.read_csv('/home/tori/behavioural-fruad-detection/data/raw/test.csv')

In [9]:
df2.head()

,transaction_id,user_id,timestamp,amount,merchant_category,country,device_id,channel,hours_since_prev_txn
0,146559,1818,1691012,19.660911,11,1,58236,1,113405.0
1,44130,1418,510173,10.125594,15,3,75185,0,37289.0
2,186330,2342,2146923,44.317939,19,28,49861,0,3370.0
3,94174,3700,1087650,34.383325,18,4,30862,1,41062.0
4,42754,2643,493774,94.826065,19,13,77512,0,161992.0

In [10]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 45531 entries, 0 to 45530
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   transaction_id        45531 non-null  int64
 1   user_id               45531 non-null  int64
 2   timestamp             45531 non-null  int64
 3   amount                45531 non-null  float64
 4   merchant_category     45531 non-null  int64
 5   country               45531 non-null  int64
 6   device_id             45531 non-null  int64
 7   channel               45531 non-null  int64
 8   hours_since_prev_txn  45531 non-null  float64
dtypes: float64(2), int64(7)
memory usage: 3.1 MB

In [11]:
test_min = df2['timestamp'].min()
test_max = df2['timestamp'].max()
train_min = df['timestamp'].min()
train_max = df['timestamp'].max()

train_min, train_max, test_min, train_max

(np.int64(6), np.int64(2874525), np.int64(70), np.int64(2874525))

In [12]:
one_user = df[df['user_id'] == 1818]
one_user

,transaction_id,user_id,timestamp,amount,merchant_category,country,device_id,channel,hours_since_prev_txn,label
8246,200288,1818,2306013,10.799825,11,9,58236,1,177088.0,0
9062,152146,1818,1755772,8.567789,11,1,58236,1,64760.0,0
13818,126330,1818,1458448,25.102442,19,1,58236,0,17753.0,0
14223,119937,1818,1384680,16.473972,11,1,58236,0,53543.0,0
14931,212348,1818,2443295,7.090206,11,0,58236,1,10887.0,0
22761,95087,1818,1098734,7.483825,11,12,58236,1,179147.0,0
27020,34692,1818,400886,5.410091,0,12,58236,0,76486.0,0
27540,229413,1818,2638778,14.809400,3,0,58236,0,13581.0,0
28724,246669,1818,2837285,25.527127,9,0,58236,0,22550.0,0
33849,79712,1818,919587,6.174141,17,12,58236,0,1248.0,0
47429,97636,1818,1128345,11.044716,11,22,58236,1,6644.0,0
48474,99967,1818,1155643,11.366749,11,6,58236,0,21733.0,0
65009,76305,1818,879817,20.935129,11,8,58236,0,87006.0,0
70904,124815,1818,1440695,16.853545,11,1,58236,0,20830.0,0
75242,228219,1818,2625197,10.833020,14,0,58236,0,24013.0,0
75911,244666,1818,2814735,13.685864,11,0,58236,0,7865.0,0
82082,157617,1818,1819214,5.636716,11,1,58236,1,63442.0,0
82309,45092,1818,521027,16.608058,11,12,58236,1,26606.0,0
87174,34858,1818,402972,14.351851,0,12,58236,0,2086.0,0
89832,184705,1818,2128925,9.544737,11,9,58236,0,168588.0,0
90712,170208,1818,1960337,18.365481,15,9,58236,0,21012.0,0
96186,209628,1818,2412401,16.491943,11,10,58236,0,89832.0,0
105609,136714,1818,1577607,7.586703,11,1,58236,0,119159.0,0
107907,201771,1818,2322569,8.009288,13,9,58236,0,16556.0,0
137625,39662,1818,458589,10.819577,11,12,58236,1,55617.0,0
140320,243964,1818,2806870,8.461123,11,0,58236,1,30557.0,0
142079,97105,1818,1121701,8.845878,11,12,58236,1,22967.0,0
145148,115218,1818,1331137,15.018878,11,1,58236,0,65564.0,0
146117,51641,1818,596247,14.457568,3,12,58236,0,75220.0,0
147236,210774,1818,2425559,17.757841,4,10,58236,0,13158.0,0
148134,4524,1818,52726,17.788061,11,4,58236,0,999.0,0
161114,123045,1818,1419865,10.987262,11,1,58236,0,35185.0,0
161473,219815,1818,2528730,13.596652,13,0,58236,1,42780.0,0
161714,12836,1818,150491,33.010191,11,4,58236,1,97765.0,0
162731,68723,1818,792811,2.608586,11,8,58236,1,3529.0,0
169657,106281,1818,1227911,7.936473,15,6,58236,1,72268.0,0
178396,20224,1818,233405,15.018893,11,4,58236,0,66443.0,0
178416,14356,1818,166962,37.474351,0,4,58236,0,16471.0,0
181371,213033,1818,2450848,13.003477,11,0,58236,1,7553.0,0
181758,107019,1818,1236680,17.147700,9,29,58236,0,8769.0,0

In [13]:
one_user = one_user.sort_values('timestamp')
one_user

,transaction_id,user_id,timestamp,amount,merchant_category,country,device_id,channel,hours_since_prev_txn,label
148134,4524,1818,52726,17.788061,11,4,58236,0,999.0,0
161714,12836,1818,150491,33.010191,11,4,58236,1,97765.0,0
178416,14356,1818,166962,37.474351,0,4,58236,0,16471.0,0
178396,20224,1818,233405,15.018893,11,4,58236,0,66443.0,0
27020,34692,1818,400886,5.410091,0,12,58236,0,76486.0,0
87174,34858,1818,402972,14.351851,0,12,58236,0,2086.0,0
137625,39662,1818,458589,10.819577,11,12,58236,1,55617.0,0
82309,45092,1818,521027,16.608058,11,12,58236,1,26606.0,0
146117,51641,1818,596247,14.457568,3,12,58236,0,75220.0,0
162731,68723,1818,792811,2.608586,11,8,58236,1,3529.0,0
65009,76305,1818,879817,20.935129,11,8,58236,0,87006.0,0
33849,79712,1818,919587,6.174141,17,12,58236,0,1248.0,0
22761,95087,1818,1098734,7.483825,11,12,58236,1,179147.0,0
142079,97105,1818,1121701,8.845878,11,12,58236,1,22967.0,0
47429,97636,1818,1128345,11.044716,11,22,58236,1,6644.0,0
48474,99967,1818,1155643,11.366749,11,6,58236,0,21733.0,0
169657,106281,1818,1227911,7.936473,15,6,58236,1,72268.0,0
181758,107019,1818,1236680,17.147700,9,29,58236,0,8769.0,0
145148,115218,1818,1331137,15.018878,11,1,58236,0,65564.0,0
14223,119937,1818,1384680,16.473972,11,1,58236,0,53543.0,0
161114,123045,1818,1419865,10.987262,11,1,58236,0,35185.0,0
70904,124815,1818,1440695,16.853545,11,1,58236,0,20830.0,0
13818,126330,1818,1458448,25.102442,19,1,58236,0,17753.0,0
105609,136714,1818,1577607,7.586703,11,1,58236,0,119159.0,0
9062,152146,1818,1755772,8.567789,11,1,58236,1,64760.0,0
82082,157617,1818,1819214,5.636716,11,1,58236,1,63442.0,0
90712,170208,1818,1960337,18.365481,15,9,58236,0,21012.0,0
89832,184705,1818,2128925,9.544737,11,9,58236,0,168588.0,0
8246,200288,1818,2306013,10.799825,11,9,58236,1,177088.0,0
107907,201771,1818,2322569,8.009288,13,9,58236,0,16556.0,0
96186,209628,1818,2412401,16.491943,11,10,58236,0,89832.0,0
147236,210774,1818,2425559,17.757841,4,10,58236,0,13158.0,0
14931,212348,1818,2443295,7.090206,11,0,58236,1,10887.0,0
181371,213033,1818,2450848,13.003477,11,0,58236,1,7553.0,0
161473,219815,1818,2528730,13.596652,13,0,58236,1,42780.0,0
75242,228219,1818,2625197,10.833020,14,0,58236,0,24013.0,0
27540,229413,1818,2638778,14.809400,3,0,58236,0,13581.0,0
140320,243964,1818,2806870,8.461123,11,0,58236,1,30557.0,0
75911,244666,1818,2814735,13.685864,11,0,58236,0,7865.0,0
28724,246669,1818,2837285,25.527127,9,0,58236,0,22550.0,0

In [14]:
one_user['my_gap'] = one_user['timestamp'].diff()
one_user

,transaction_id,user_id,timestamp,amount,merchant_category,country,device_id,channel,hours_since_prev_txn,label,my_gap
148134,4524,1818,52726,17.788061,11,4,58236,0,999.0,0,NaN
161714,12836,1818,150491,33.010191,11,4,58236,1,97765.0,0,97765.0
178416,14356,1818,166962,37.474351,0,4,58236,0,16471.0,0,16471.0
178396,20224,1818,233405,15.018893,11,4,58236,0,66443.0,0,66443.0
27020,34692,1818,400886,5.410091,0,12,58236,0,76486.0,0,167481.0
87174,34858,1818,402972,14.351851,0,12,58236,0,2086.0,0,2086.0
137625,39662,1818,458589,10.819577,11,12,58236,1,55617.0,0,55617.0
82309,45092,1818,521027,16.608058,11,12,58236,1,26606.0,0,62438.0
146117,51641,1818,596247,14.457568,3,12,58236,0,75220.0,0,75220.0
162731,68723,1818,792811,2.608586,11,8,58236,1,3529.0,0,196564.0
65009,76305,1818,879817,20.935129,11,8,58236,0,87006.0,0,87006.0
33849,79712,1818,919587,6.174141,17,12,58236,0,1248.0,0,39770.0
22761,95087,1818,1098734,7.483825,11,12,58236,1,179147.0,0,179147.0
142079,97105,1818,1121701,8.845878,11,12,58236,1,22967.0,0,22967.0
47429,97636,1818,1128345,11.044716,11,22,58236,1,6644.0,0,6644.0
48474,99967,1818,1155643,11.366749,11,6,58236,0,21733.0,0,27298.0
169657,106281,1818,1227911,7.936473,15,6,58236,1,72268.0,0,72268.0
181758,107019,1818,1236680,17.147700,9,29,58236,0,8769.0,0,8769.0
145148,115218,1818,1331137,15.018878,11,1,58236,0,65564.0,0,94457.0
14223,119937,1818,1384680,16.473972,11,1,58236,0,53543.0,0,53543.0
161114,123045,1818,1419865,10.987262,11,1,58236,0,35185.0,0,35185.0
70904,124815,1818,1440695,16.853545,11,1,58236,0,20830.0,0,20830.0
13818,126330,1818,1458448,25.102442,19,1,58236,0,17753.0,0,17753.0
105609,136714,1818,1577607,7.586703,11,1,58236,0,119159.0,0,119159.0
9062,152146,1818,1755772,8.567789,11,1,58236,1,64760.0,0,178165.0
82082,157617,1818,1819214,5.636716,11,1,58236,1,63442.0,0,63442.0
90712,170208,1818,1960337,18.365481,15,9,58236,0,21012.0,0,141123.0
89832,184705,1818,2128925,9.544737,11,9,58236,0,168588.0,0,168588.0
8246,200288,1818,2306013,10.799825,11,9,58236,1,177088.0,0,177088.0
107907,201771,1818,2322569,8.009288,13,9,58236,0,16556.0,0,16556.0
96186,209628,1818,2412401,16.491943,11,10,58236,0,89832.0,0,89832.0
147236,210774,1818,2425559,17.757841,4,10,58236,0,13158.0,0,13158.0
14931,212348,1818,2443295,7.090206,11,0,58236,1,10887.0,0,17736.0
181371,213033,1818,2450848,13.003477,11,0,58236,1,7553.0,0,7553.0
161473,219815,1818,2528730,13.596652,13,0,58236,1,42780.0,0,77882.0
75242,228219,1818,2625197,10.833020,14,0,58236,0,24013.0,0,96467.0
27540,229413,1818,2638778,14.809400,3,0,58236,0,13581.0,0,13581.0
140320,243964,1818,2806870,8.461123,11,0,58236,1,30557.0,0,168092.0
75911,244666,1818,2814735,13.685864,11,0,58236,0,7865.0,0,7865.0
28724,246669,1818,2837285,25.527127,9,0,58236,0,22550.0,0,22550.0

In [15]:
one_user[['timestamp', 'my_gap', 'hours_since_prev_txn']]

        timestamp    my_gap  hours_since_prev_txn
148134      52726       NaN                 999.0
161714     150491   97765.0               97765.0
178416     166962   16471.0               16471.0
178396     233405   66443.0               66443.0
27020      400886  167481.0               76486.0
87174      402972    2086.0                2086.0
137625     458589   55617.0               55617.0
82309      521027   62438.0               26606.0
146117     596247   75220.0               75220.0
162731     792811  196564.0                3529.0
65009      879817   87006.0               87006.0
33849      919587   39770.0                1248.0
22761     1098734  179147.0              179147.0
142079    1121701   22967.0               22967.0
47429     1128345    6644.0                6644.0
48474     1155643   27298.0               21733.0
169657    1227911   72268.0               72268.0
181758    1236680    8769.0                8769.0
145148    1331137   94457.0               65564.0
14223     1384680   53543.0               53543.0
161114    1419865   35185.0               35185.0
70904     1440695   20830.0               20830.0
13818     1458448   17753.0               17753.0
105609    1577607  119159.0              119159.0
9062      1755772  178165.0               64760.0
82082     1819214   63442.0               63442.0
90712     1960337  141123.0               21012.0
89832     2128925  168588.0              168588.0
8246      2306013  177088.0              177088.0
107907    2322569   16556.0               16556.0
96186     2412401   89832.0               89832.0
147236    2425559   13158.0               13158.0
14931     2443295   17736.0               10887.0
181371    2450848    7553.0                7553.0
161473    2528730   77882.0               42780.0
75242     2625197   96467.0               24013.0
27540     2638778   13581.0               13581.0
140320    2806870  168092.0               30557.0
75911     2814735    7865.0                7865.0
28724     2837285   22550.0               22550.0

In [16]:
400886 - 76486

324400

In [17]:
filter_df2 = df2[df2['user_id'] == 1818]
filter_df2

,transaction_id,user_id,timestamp,amount,merchant_category,country,device_id,channel,hours_since_prev_txn
0,146559,1818,1691012,19.660911,11,1,58236,1,113405.0
4207,28125,1818,324400,10.954236,11,4,58236,1,90995.0
6711,226044,1818,2601184,19.090409,11,0,58236,0,72454.0
13626,235518,1818,2710397,8.444852,11,0,58236,0,71619.0
23087,168285,1818,1939325,9.075470,11,9,58236,1,29932.0
26188,42814,1818,494421,5.095317,11,12,58236,0,35832.0
31232,98148,1818,1133910,13.789907,3,6,58236,1,5565.0
38233,211412,1818,2432408,18.136065,2,0,58236,0,6849.0
38521,241329,1818,2776313,16.979575,11,0,58236,1,65916.0
40103,68428,1818,789282,12.680154,11,8,58236,0,193035.0
42458,214479,1818,2467536,31.124441,11,0,58236,0,16688.0
44347,165566,1818,1909393,7.820848,11,9,58236,1,90179.0

In [18]:
df['label']. value_counts(normalize=True)

label
0    0.983583
1    0.016417
Name: proportion, dtype: float64

In [19]:
df.groupby('user_id').size().describe()

count    5000.000000
mean       36.425000
std         5.956431
min        18.000000
25%        32.000000
50%        36.000000
75%        40.000000
max        60.000000
dtype: float64

In [20]:
train_min, train_max, test_min, test_max

(np.int64(6), np.int64(2874525), np.int64(70), np.int64(2874525))